### ISSUE TITLE
Minimum Perl version should be 5.14, current 5.6

### ISSUE THREAD

**Issue by jwrightecs** [shlomif/CSV2Chart#2]
lib/App/CSV2Chart/Command/svg.pm  uses non-destructive substitution (s//r) introduced in 5.14
lib/App/CSV2Chart/API/ToXLSX.pm uses 'each' over an array, introduced in 5.12

**Comment by shlomif** [comment]
Thanks for the report! This should be fixed in the 0.8.2 release.

**Comment by shlomif** [comment]
Closing as fixed.
